export const ENV = {
  API_URL: process.env.EXPO_PUBLIC_API_URL || 'http://localhost:8000/api',
  FRONTEND_KEY: process.env.EXPO_PUBLIC_FRONTEND_KEY || '',
  APP_SCHEME: process.env.EXPO_PUBLIC_APP_SCHEME || 'alemancenter',
  DEFAULT_COUNTRY_ID: process.env.EXPO_PUBLIC_DEFAULT_COUNTRY_ID || '1',
  DEFAULT_COUNTRY_CODE: process.env.EXPO_PUBLIC_DEFAULT_COUNTRY_CODE || 'jo',
  DEFAULT_LOCALE: process.env.EXPO_PUBLIC_DEFAULT_LOCALE || 'ar',
  SITE_URL: process.env.EXPO_PUBLIC_SITE_URL || 'https://alemancenter.com',

  // Google Sign-In
  GOOGLE_WEB_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID || '',

  // AdMob Configuration
  ADMOB_ANDROID_APP_ID: process.env.EXPO_PUBLIC_ADMOB_ANDROID_APP_ID || '',
  ADMOB_IOS_APP_ID: process.env.EXPO_PUBLIC_ADMOB_IOS_APP_ID || '',
  ADMOB_ANDROID_BANNER_ID: process.env.EXPO_PUBLIC_ADMOB_ANDROID_BANNER_ID || '',
  ADMOB_IOS_BANNER_ID: process.env.EXPO_PUBLIC_ADMOB_IOS_BANNER_ID || '',
  ADMOB_ANDROID_INTERSTITIAL_ID: process.env.EXPO_PUBLIC_ADMOB_ANDROID_INTERSTITIAL_ID || '',
  ADMOB_IOS_INTERSTITIAL_ID: process.env.EXPO_PUBLIC_ADMOB_IOS_INTERSTITIAL_ID || ''
};
